title: A Platform for Everyone
email: s2231321@ed.ac.uk
description: A Platform for Everyone
theme: minima

author:
  name: Henry Yip
  email: "s2231321@ed.ac.uk"


baseurl: "" 
url: "https://henry-yip.github.io/" 
github_username:  

remote_theme: jekyll/minima@3cdd14dff1216f561c68329e0b7420c2dc9b796a

minima:
  social_links:
    github: 
    linkedin: 
    youtube_channel: 
    youtube_channel_name: 

markdown: kramdown

kramdown:
  math_engine: katex

gems: ['jekyll-offline']

permalink: /:year/:month/:day/:title:output_ext

minima:
  skin: solarized

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-archives

algolia:
   application_id: G0D1JTWKBL
   index_name: ScienceProject
   search_only_api_key: 6eab7e21586f15703940cf9304020502 

disqus:
    shortname: https-henry-yip-github-io

